#!/usr/bin/env zsh
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export PRODUCE_COMPANY_NAME="Khang Nguyen"
export EXPO_IOS_DIST_P12_PASSWORD="0nYIk+PyggMIkNJXanowrw=="
turtle build:ios \
    --team-id PM9Q9WAP3Q \
    --dist-p12-path turtle/dist.p12 \
    --provisioning-profile-path turtle/dist.mobileprovision \
    -u brew4k \
    -p Archbtw2@expo \
    --type archive
