#!/usr/bin/env zsh

mkdir Slide
qrcode   _5qRr42ejYHUKo0CxYu_ -o Slide/start.png
qrcode   _8N6E4jwqerhmSORIwR_ -o Slide/pause.png
qrcode   _HteWlblZIXoNfiTBwE_ -o Slide/resume.png
qrcode   _WOvJ8EMaFRRJPCv7B5_ -o Slide/stop-final.png
qrcode   _UUWUI7MTwfaZKKLyoP_ -o Slide/completeStage.png

mkdir Relay2Maze
qrcode   _WcgQoo5OiPRGzlKFph_ -o Relay2Maze/start.png
qrcode   _hL9oj38xkMDfCL4uej_ -o Relay2Maze/pause.png
qrcode   _NZarAtJsx1xWFgRhBm_ -o Relay2Maze/resume.png
qrcode   _lKDmVZ6aUKBi5ZSBkP_ -o Relay2Maze/stop-final.png
qrcode   _8SiYO5HUSgdza1BzyJ_ -o Relay2Maze/completeStage.png

mkdir SotongHouze
qrcode   _jH59pUJ7iRBH8Hgptr_ -o SotongHouze/start.png
qrcode   _IMsHhYefxYkQPggMry_ -o SotongHouze/pause.png
qrcode   _499hPsXHdLj5auIC3Q_ -o SotongHouze/resume.png
qrcode   _XTNo7Arxm7eNZ4jlVU_ -o SotongHouze/stop-final.png
qrcode   _1lqGSmLYlhq89e8Caz_ -o SotongHouze/completeStage.png

mkdir SnakeandLadders
qrcode   _0EtRCaTalVyHaY4gIh_ -o SnakeandLadders/start.png
qrcode   _J2uRsLVoi03ecTbfL6_ -o SnakeandLadders/pause.png
qrcode   _oekwozowVWiMexVgzq_ -o SnakeandLadders/resume.png
qrcode   _rXPSVli1KANW0maIjL_ -o SnakeandLadders/stop-final.png
qrcode   _RTLTHLg6darz80ZZb7_ -o SnakeandLadders/completeStage.png

mkdir GOLF
qrcode   _trgSYWtZ5uaJF3fqSd_ -o GOLF/start.png
qrcode   _1KYf4ohFBQq2uvwVSw_ -o GOLF/pause.png
qrcode   _yhLxIj25q9i50XgwY4_ -o GOLF/resume.png
qrcode   _xiITteYpv9ts5eAD3o_ -o GOLF/stop-final.png
qrcode   _MmbjrgcauDBbSRdkfd_ -o GOLF/completeStage.png

mkdir NerfBattle
qrcode   _vj3aQ4IrxGISQ2Q6UY_ -o NerfBattle/start.png
qrcode   _A2Inl1D0RuyqyxtNzl_ -o NerfBattle/pause.png
qrcode   _jVJ6SFayybvaAz4jDx_ -o NerfBattle/resume.png
qrcode   _E48cuhkOfPAZ4k9CaB_ -o NerfBattle/stop-final.png
qrcode   _GBiQvd7HHwmo5F5iB8_ -o NerfBattle/completeStage.png
