#!/usr/bin/env zsh

rm -rf Slide
rm -rf Relay2Maze
rm -rf SotongHouze
rm -rf SnakeandLadders
rm -rf GOLF
rm -rf NerfBattle

mkdir Slide
mkdir Relay2Maze
mkdir SotongHouze
mkdir SnakeandLadders
mkdir GOLF
mkdir NerfBattle

qrcode _5qRr42ejYHUKo0CxYu_ -s 16 -o Slide/start.png
qrcode _8N6E4jwqerhmSORIwR_ -s 16 -o Slide/pause.png
qrcode _HteWlblZIXoNfiTBwE_ -s 16 -o Slide/resume.png
qrcode _WOvJ8EMaFRRJPCv7B5_ -s 16 -o Slide/stop-final.png
qrcode _UUWUI7MTwfaZKKLyoP_ -s 16 -o Slide/completeStage.png
qrcode _WcgQoo5OiPRGzlKFph_ -s 16 -o Relay2Maze/start.png
qrcode _hL9oj38xkMDfCL4uej_ -s 16 -o Relay2Maze/pause.png
qrcode _NZarAtJsx1xWFgRhBm_ -s 16 -o Relay2Maze/resume.png
qrcode _lKDmVZ6aUKBi5ZSBkP_ -s 16 -o Relay2Maze/stop-final.png
qrcode _8SiYO5HUSgdza1BzyJ_ -s 16 -o Relay2Maze/completeStage.png
qrcode _jH59pUJ7iRBH8Hgptr_ -s 16 -o SotongHouze/start.png
qrcode _IMsHhYefxYkQPggMry_ -s 16 -o SotongHouze/pause.png
qrcode _499hPsXHdLj5auIC3Q_ -s 16 -o SotongHouze/resume.png
qrcode _XTNo7Arxm7eNZ4jlVU_ -s 16 -o SotongHouze/stop-final.png
qrcode _1lqGSmLYlhq89e8Caz_ -s 16 -o SotongHouze/completeStage.png
qrcode _0EtRCaTalVyHaY4gIh_ -s 16 -o SnakeandLadders/start.png
qrcode _J2uRsLVoi03ecTbfL6_ -s 16 -o SnakeandLadders/pause.png
qrcode _oekwozowVWiMexVgzq_ -s 16 -o SnakeandLadders/resume.png
qrcode _rXPSVli1KANW0maIjL_ -s 16 -o SnakeandLadders/stop-final.png
qrcode _RTLTHLg6darz80ZZb7_ -s 16 -o SnakeandLadders/completeStage.png
qrcode _trgSYWtZ5uaJF3fqSd_ -s 16 -o GOLF/start.png
qrcode _1KYf4ohFBQq2uvwVSw_ -s 16 -o GOLF/pause.png
qrcode _yhLxIj25q9i50XgwY4_ -s 16 -o GOLF/resume.png
qrcode _xiITteYpv9ts5eAD3o_ -s 16 -o GOLF/stop-final.png
qrcode _MmbjrgcauDBbSRdkfd_ -s 16 -o GOLF/completeStage.png
qrcode _vj3aQ4IrxGISQ2Q6UY_ -s 16 -o NerfBattle/start.png
qrcode _A2Inl1D0RuyqyxtNzl_ -s 16 -o NerfBattle/pause.png
qrcode _jVJ6SFayybvaAz4jDx_ -s 16 -o NerfBattle/resume.png
qrcode _E48cuhkOfPAZ4k9CaB_ -s 16 -o NerfBattle/stop-final.png
qrcode _GBiQvd7HHwmo5F5iB8_ -s 16 -o NerfBattle/completeStage.png
